# libcgroup cgrules.conf(5) examples.
student		devices		/usergroup/students
student:cp	devices		/usergroup/students/cp
@admin		*		admingroup/
peter		cpu		test1/
%		memory		test2/
*		*		default/
*:*		*		jobs/%U-%P	nore
