# libcgroup cgconfig.conf(5) Example 2 + permissions, cgroup v1 era syntax.
mount {
	cpu = /mnt/cgroups/cpu;
	cpuacct = /mnt/cgroups/cpu;
	"name=noctrl" = /mnt/cgroups/noctrl;
}

group daemons/www {
	perm {
		task {
			uid = root;
			gid = webmaster;
			fperm = 770;
		}
		admin {
			uid = root;
			gid = root;
			dperm = 775;
			fperm = 744;
		}
	}
	cpu {
		cpu.shares = "1000";
	}
}

group daemons/ftp {
	perm {
		task {
			uid = root;
			gid = ftpmaster;
			fperm = 774;
		}
		admin {
			uid = root;
			gid = root;
			dperm = 755;
			fperm = 700;
		}
	}
	cpu {
		cpu.shares = "500";
	}
}
