# libcgroup cgconfig.conf(5) template example: per-user student leaves.
mount {
	cpu = /mnt/cgroups/cpu;
	cpuacct = /mnt/cgroups/cpuacct;
}

group students {
	cpuacct {
	}
	cpu {
	}
}

template students/%u {
	perm {
		task {
			uid = %u;
			gid = students;
			fperm = 775;
		}
		admin {
			uid = root;
			gid = root;
			dperm = 750;
		}
	}
	cpuacct {
	}
	cpu {
	}
}

# The root group can be configured by naming it '.'.
group . {
	perm {
		task {
			uid = root;
			gid = operator;
		}
		admin {
			uid = root;
			gid = operator;
		}
	}
}
